### ISSUE TITLE
Arguendo?

### ISSUE THREAD

**Issue by kiphale** [ABA-Center-for-Human-Rights/international-criminal-justice-today#31] opened 2014-12-07 20:08 UTC
@budparr If someone finds themselves in one particular arguendo, what do you think is the best way for them to get out to see other ones? A link to the other ones or something that says "Past Arguendo Roundtables" on righthand bar?

http://www.international-criminal-justice-today.org/arguendo/question/African-Union-and-international-criminal-justice:-where-does-it-go-from-here/

**Comment by budparr** [comment] 2015-01-07 15:14
I'll add a link to the bottom of the individual page.

**Comment by kiphale** [comment] 2015-04-20 21:45
Ok @budparr "on the road" ;)

**Comment by budparr** [comment] 2015-04-21 03:22
duplicate of #50

**Closed by budparr** 2015-04-21 03:22 UTC
